- name: Create Azure Kubernetes Cluster to host gandalfApp
  hosts: control
  connection: ssh
  vars:
    auth_source: "cli"

  tasks:
    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: adcash-assignment
        allocation_method: Static
        name: gandalfIP
        sku: Standard
        location: switzerlandnorth
      register: output_ip_address
    - name: Store public IP for later
      set_fact:
        aks_public_ip: "{{ output_ip_address.state.ip_address }}"

    - name: Public IP display
      debug:
        msg: "The public IP is {{ aks_public_ip }}."

    - name: Create Network Security Group that allows HTTP and SSH
      azure_rm_securitygroup:
        resource_group: adcash-assignment
        name: Ansible-Control-Node-nsg
        rules:
          - name: Allow_HTTP_Traffic
            protocol: TCP
            destination_port_range: 80
            access: Allow
            priority: 1001
            direction: Inbound
          - name: SSH
            protocol: TCP
            destination_port_range: 22
            access: Allow
            priority: 1010
            direction: Inbound

    - name: Create subnet for Node.js app
      azure.azcollection.azure_rm_subnet:
        name: nodeAppSubnet
        resource_group: adcash-assignment
        virtual_network_name: Ansible-Control-Node-vnet
        address_prefix: 10.0.1.0/24
        security_group: Ansible-Control-Node-nsg
        state: present

    - name: Generate SSH key pair for AKS access
      ansible.builtin.openssh_keypair:
        path: ~/.ssh/id_rsa
        type: rsa
        size: 4096
        mode: '0600'

    - name: Get public SSH key
      shell: cat ~/.ssh/id_rsa.pub
      register: ssh_key_cat
      changed_when: false

    - set_fact:
        ssh_key: "{{ ssh_key_cat.stdout }}"

    - name: Create a managed Azure Container Services (AKS) cluster
      vars:
        resource_group: adcash-assignment
        location: switzerlandnorth
        aks_name: gandalfCluster
        username: adcash
        ssh_key: "{{ ssh_key }}"
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
        aks_version: 1.33.1
      azure_rm_aks:
        name: "{{ aks_name }}"
        location: "{{ location }}"
        resource_group: "{{ resource_group }}"
        dns_prefix: "{{ aks_name }}"
        kubernetes_version: "{{ aks_version }}"
        linux_profile:
          admin_username: "{{ username }}"
          ssh_key: "{{ ssh_key }}"
        service_principal:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
        agent_pool_profiles:
          - name: userpool
            count: 1
            vm_size: Standard_A2_v2
          - name: systempool
            count: 1
            vm_size: Standard_A2_v2
            mode: System
            
    - name: Install kubectl (version pinned)
      shell: |
        if ! command -v kubectl &>/dev/null; then
          VERSION="v1.29.3"
          curl -LO "https://dl.k8s.io/release/$VERSION/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
        else
          echo "kubectl already installed"
        fi
      args:
        executable: /bin/bash
      changed_when: false


- name: Deploy GandalfApp to AKS
  hosts: control
  connection: ssh
  vars:
    deployment_manifest: deployment.yaml
    service_manifest: service.yaml
    resource_group: adcash-assignment
    cluster_name: GandalfCluster

  tasks:
    - name: Clone GitHub repo
      git:
        repo: 'https://github.com/AnirudhBabu/Adcash-Assignment.git'
        dest: '~/adcash-assignment'
        version: main

    - name: Get AKS credentials for kubectl
      shell: |
        az aks get-credentials \
          --resource-group {{ resource_group }} \
          --name {{ cluster_name }} \
          --overwrite-existing
      changed_when: true

    - name: Create GHCR pull secret
      shell: |
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=anirudhbabu \
          --docker-password={{ GHCR_PAT }} \
          --docker-email=anirudhbabu2001@gmail.com || echo "ghcr-secret already exists"
      args:
        executable: /bin/bash
      changed_when: false

    - name: Render service manifest with correct values
      template:
        src: ./service.yaml.j2
        dest: ./service.yaml

    - name: Render deployment manifest with correct values
      template:
        src: ./deployment.yaml.j2
        dest: ./deployment.yaml

    - name: Apply Kubernetes Deployment
      shell: kubectl apply -f ./{{ deployment_manifest }}

    - name: Apply Kubernetes Service
      shell: kubectl apply -f ./{{ service_manifest }}

    - name: Wait for Gandalf pod to be live
      shell: |
        kubectl rollout status deployment/gandalf-app
      register: rollout_status
      until: rollout_status.stdout.find("successfully rolled out") != -1
      retries: 5
      delay: 5

- name: Deploy a VM for Prometheus Server
  hosts: control
  connection: ssh
  tasks:
    - name: Generate SSH key pair for Prometheus VM
      community.crypto.openssh_keypair:
        path: ~/.ssh/prometheus_id_rsa
        type: rsa
        size: 4096
        mode: '0600'

    - name: Get public SSH key
      shell: cat ~/.ssh/prometheus_id_rsa.pub
      register: ssh_key_prom
      changed_when: false

    - set_fact:
        prom_ssh_key: "{{ ssh_key_prom.stdout }}"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: adcash-assignment
        location: swedencentral
        name: prometheus-vnet
        address_prefixes: "10.0.0.0/16"

    - name: Add subnet
      azure_rm_subnet:
        resource_group: adcash-assignment
        name: prom-subnet
        address_prefix: "10.0.1.0/24"
        virtual_network: prometheus-vnet

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: adcash-assignment
        location: swedencentral
        allocation_method: Static
        sku: Standard
        name: promPublicIP
      register: output_ip_address_prom
    
    - name: Public IP of VM
      debug:
        msg: "The public IP of prometheus server is {{ output_ip_address_prom.state.ip_address }}."

    - name: Write Prometheus public IP to disk
      copy:
        content: "{{ output_ip_address_prom.state.ip_address }}"
        dest: /tmp/prometheus_ip.txt

    - name: Create Network Security Group that allows SSH and HTTP
      azure_rm_securitygroup:
        resource_group: adcash-assignment
        name: prometheus-nsg
        rules:
          - name: Allow_SSH
            protocol: TCP
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: allow_outbound_http
            access: Allow
            direction: Outbound
            protocol: TCP
            priority: 1010
            destination_port_range: '80'
          - name: allow_inbound_to_prom_port
            access: Allow
            direction: Inbound
            protocol: TCP
            priority: 1020
            destination_port_range: '9090'
          - name: allow_inbound_http
            access: Allow
            direction: Inbound
            protocol: TCP
            priority: 1025
            destination_port_range: '80'

    - name: Create virtual network interface card
      azure_rm_networkinterface:
        resource_group: adcash-assignment
        name: prometheusNIC
        virtual_network: prometheus-vnet
        location: swedencentral
        subnet: prom-subnet
        ip_configurations:
          - name: ipconfig1
            public_ip_name: promPublicIP
        security_group: prometheus-nsg

    - name: Create a VM
      azure_rm_virtualmachine:
        resource_group: adcash-assignment
        name: prom-server
        vm_size: Standard_A2_v2
        location: swedencentral
        admin_username: promSnoop
        network_interfaces: prometheusNIC
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/promSnoop/.ssh/authorized_keys
            key_data: "{{ prom_ssh_key }}"
        image:
          offer: 0001-com-ubuntu-server-jammy
          publisher: Canonical
          sku: 22_04-lts
          version: latest
      register: prom_vm