apiVersion: apps/v1
kind: Deployment
metadata:
  name: gandalf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gandalf
  template:
    metadata:
      labels:
        app: gandalf
    spec:
      containers:
      - name: gandalf
        image: ghcr.io/anirudhbabu/Adcash-Assignment/gandalf-app:latest
        imagePullSecrets:
          - name: ghcr-secret
        ports:
        - containerPort: 80
