apiVersion: v1
kind: Service
metadata:
  name: gandalf-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: yourResourceGroup
spec:
  type: LoadBalancer
  loadBalancerIP: yourStaticIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: gandalf
